### PR TITLE
Fix encoding issues on Windows

### PR DESCRIPTION
**Pull request by avskor**
Fix [Encoding issues on Windows](https://github.com/spring-io/spring-asciidoctor-backends/issues/25)

### CODE REVIEW

**Comment by eallais** [comment]
Hello.
Could we have a release for this fix ?

**Comment by wilkinsona** [comment]
I'd forgotten about this when I opened and fixed https://github.com/spring-io/spring-asciidoctor-backends/issues/80. I think those changes may address this problem. @eallais, can you please try 0.0.6-SNAPSHOT that's available from https://repo.spring.io/snapshot and let us know if it works for you?

**Comment by eallais** [comment]
@wilkinsona Yes it works for me with the 0.0.6-SNAPSHOT

**Comment by wilkinsona** [comment]
Thanks, @eallais. @avskor, sorry for overlooking this when I filed and fixed #80.

**Comment by wilkinsona** [comment]
@eallais 0.0.6 is now available from Maven Central.

**Pull request closed without merging**
